/** Render an incident report as Markdown. */
import type { IncidentReport } from "./incident.js";

function iso(at: number): string {
  try {
    return new Date(at).toISOString();
  } catch {
    return String(at);
  }
}

export function renderMarkdown(r: IncidentReport): string {
  const s = r.summary;
  const lines: string[] = [
    "# NOAH Incident Report",
    "",
    `- **Host:** ${r.host}`,
    `- **Generated:** ${iso(r.generatedAt)}`,
    "",
    "## Summary",
    "",
    `- Actions run: **${s.actions}** (${s.failures} failed)`,
    `- Changes made: **${s.changes}** — ${s.reversible} reversible, ${s.undone} undone`,
    "",
    "## Timeline",
    "",
  ];

  if (r.timeline.length === 0) lines.push("_No recorded activity._");
  for (const e of r.timeline) {
    const mark = e.kind === "change" ? "±" : e.kind === "undo" ? "↩" : e.ok === false ? "✗" : "·";
    lines.push(`- \`${iso(e.at)}\` ${mark} ${e.text}`);
  }

  lines.push("", "## Changes", "");
  if (r.changes.length === 0) lines.push("_No system changes were recorded._");
  for (const c of r.changes) {
    const state = c.undone ? "undone" : c.reversible ? "reversible" : "not reversible";
    lines.push(`- ${c.desc} — _${state}_`);
  }

  lines.push("", "---", "_Generated by NOAH — every action gated, audited, and reversible._");
  return lines.join("\n");
}
